


export const allNav = [
    {
       id: 1,
       title: "Dashboard",
       role: "admin",
       icon: "dashboard", 
       path: "/admin/dashboard",
    },
    {
       id: 2,
       title: "Orders",
       role: "admin",
       icon: "shopping_cart", 
       path: "/admin/dashboard/orders",
    },
    {
       id: 3,
       title: "Category",
       role: "admin",
       icon: "category", 
       path: "/admin/dashboard/category",
    },
    {
         id: 4,
         title: "Sellers",
         role: "admin",
         icon: "group",
         path: "/admin/dashboard/sellers",
    },
    {
       id: 5,
       title: "Payment Requests",
       role: "admin",
       icon: "payment",
       path: "/admin/dashboard/payment-requests",
    },
    {
       id: 6,
       title: "Deactive Sellers",
       role: "admin",
       icon: "person_remove",
       path: "/admin/dashboard/deactive-sellers",
    },
    {
       id: 7,
       title: "Sellers Request",
       role: "admin",
       icon: "group_add",
    //    icon: "graph_1",
       path: "/admin/dashboard/seller-requests",
    },
    {
       id: 8,
       title: "Live Chat",
       role: "admin",
       icon: "forum",
       path: "/admin/dashboard/chat-sellers",
    },
    {
      id: 9,
      title: "Dashboard",
      role: "seller",
      icon: "dashboard", 
      path: "/seller/dashboard",
   },
    {
      id: 10,
      title: "Add Product",
      role: "seller",
      icon: "add_circle", 
      path: "/seller/dashboard/add-product",
   },
    {
      id: 11,
      title: "All Product",
      role: "seller",
      icon: "add_circle", 
      path: "/seller/dashboard/all-product",
   },
    {
      id: 12,
      title: "Discount Product",
      role: "seller",
      icon: "add_circle", 
      path: "/seller/dashboard/discount-product",
   },
    {
      id: 13,
      title: "Orders",
      role: "seller",
      icon: "add_circle", 
      path: "/seller/dashboard/orders",
   },
    {
      id: 14,
      title: "Payments",
      role: "seller",
      icon: "add_circle", 
      path: "/seller/dashboard/payments",
   },
    {
      id: 15,
      title: "Chat-Customer",
      role: "seller",
      icon: "add_circle", 
      path: "/seller/dashboard/chat-customer",
   },
    {
      id: 16,
      title: "Chat-Support",
      role: "seller",
      icon: "add_circle", 
      path: "/seller/dashboard/chat-support",
   },
];